# Generated by Django 4.0 on 2024-03-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(null=True, upload_to='profile-pictures/'),
        ),
    ]
