# Generated by Django 4.0 on 2024-03-11 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('elearning', '0002_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(null=True, upload_to='static/profile-pictures/'),
        ),
        migrations.CreateModel(
            name='CourseMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(null=True, upload_to='static/course-materials/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='material',
            field=models.ManyToManyField(related_name='course', to='elearning.CourseMaterials'),
        ),
    ]
