# Generated by Django 4.0 on 2024-03-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_alter_profile_picture_coursematerials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='material',
        ),
        migrations.AddField(
            model_name='coursematerials',
            name='course',
            field=models.ManyToManyField(to='elearning.Course'),
        ),
    ]
