# Generated by Django 4.0 on 2024-03-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerials',
            name='material',
            field=models.FileField(null=True, upload_to='elearning/static/course-materials/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='placeholder', null=True, upload_to='STATIC_URL/profile-pictures/'),
        ),
    ]
