# Generated by Django 4.0 on 2024-03-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='/static/placeholder.jpg', null=True, upload_to='profile-pictures/'),
        ),
    ]
