# Generated by Django 4.0 on 2024-03-11 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('elearning', '0009_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerials',
            name='material',
            field=models.FileField(null=True, upload_to='static/course-materials/'),
        ),
        migrations.AlterField(
            model_name='coursematerials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='static/placeholder.jpg', null=True, upload_to='static/profile-pictures/'),
        ),
    ]
