# Generated by Django 4.0 on 2024-03-11 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_alter_coursematerials_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerials',
            name='course',
        ),
        migrations.AddField(
            model_name='coursematerials',
            name='course',
            field=models.ForeignKey(default=(1), on_delete=django.db.models.deletion.DO_NOTHING, to='elearning.course'),
            preserve_default=False,
        ),
    ]
