# Generated by Django 4.0 on 2024-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_remove_coursematerials_course_coursematerials_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerials',
            name='material',
            field=models.FileField(default=1, upload_to='static/course-materials/'),
            preserve_default=False,
        ),
    ]
